services:
  evolution_proxy:
    image: nginx:latest
    container_name: evolution_proxy
    ports:
      - "8081:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - evolution-api
    networks:
      - default
